# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_mocha"

# Inserts a blank line between shell prompts
add_newline = true
scan_timeout = 10

format = """$directory\
          $git_branch\
          $git_commit\
          $git_state\
          $git_status\
          $golang\
          $helm\
          $java\
          $nodejs\
          $python\
          $red\
          $ruby\
          $rust\
          $kubernetes\
          $custom\
          $cmd_duration\
          $lua\
          $time\
          $line_break\
          $jobs\
          $status\
          $shell\
          $character"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➔](bold green)"    # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➔](bold red)"
vimcmd_symbol = "[←](bold green)"
vimcmd_replace_one_symbol = "[←](bold purple)"
vimcmd_replace_symbol = "[←](bold purple)"
vimcmd_visual_symbol = "[←](bold yellow)"

[time]
disabled = false
time_format = '%R'
format = '[\[$time\]]($style) '
style = "gray"

[username]
style_user = "purple bold"
style_root = "red bold"
format = "[$user]($style) in "
disabled = true
show_always = true

[shell]
format = 'in [$indicator \]]($style) '
disabled = true
style = "white dimmed"

[status]
# format = '[$symbol $signal_name\($signal_number\)]($style) '
format = '[$symbol]($style) '
map_symbol = true
disabled = false

[cmd_duration]
show_notifications = false
min_time = 1_000
format = "took [$duration](bold yellow) "
min_time_to_notify = 70_000

[sudo]
style = "bold red"
symbol = "root "
disabled = false

[memory_usage]
disabled = true
threshold = 50
format = "with [${ram_pct}]($style) $symbol"

[git_commit]
tag_disabled = true
only_detached = false
disabled = false
commit_hash_length = 8

[kubernetes]
disabled = false
symbol = '⎈ '
format = '[$symbol$context \($namespace\)]($style) '

[python]
pyenv_version_name = false

[golang]
#symbol = 'ʕ◔ϖ◔ʔ '

[rust]

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
